//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryMan
    {
        public int Did { get; set; }
        public string DName { get; set; }
        public string DEmail { get; set; }
        public string DPassword { get; set; }
        public string DPhone { get; set; }
        public string DStatus { get; set; }
        public int DOrderid { get; set; }
        public int DSalay { get; set; }
        public string DSchedule { get; set; }
        public Nullable<int> EId { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
